version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${SPRING_RABBITMQ_USERNAME:-capacita_rabbit}
      RABBITMQ_DEFAULT_PASS: ${SPRING_RABBITMQ_PASSWORD:-CapacitaRabbit123}  
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: unless-stopped

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"  # Porta SMTP (para envio de emails pelo backend)
      - "8025:8025"  # Painel web do Mailhog
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: redis
    command: ["redis-server", "--save", "60", "100", "--loglevel", "warning"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  api:
    image: amazoncorretto:21
    container_name: api-spring
    command: sh -c "mkdir -p /usr/share/api && java -jar /usr/share/api/app.jar"
    volumes:
      - /usr/share/api:/usr/share/api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/${DATABASE_NAME:-capacita}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: ${DATABASE_USER:-capacita_app}
      SPRING_DATASOURCE_PASSWORD: ${DATABASE_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${HIBERNATE_DDL_AUTO:-none}
      SPRING_JPA_SHOW_SQL: ${SHOW_SQL:-false}
      AWS_REGION: ${AWS_REGION:-us-east-1}
      # AWS Credentials - Se não definidas, o SDK usa automaticamente a IAM Role da EC2
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN:-}
      AWS_S3_BUCKET_BRONZE: ${AWS_S3_BUCKET_BRONZE}
      AWS_S3_BUCKET_SILVER: ${AWS_S3_BUCKET_SILVER}
      AWS_S3_BUCKET_GOLD: ${AWS_S3_BUCKET_GOLD}
      AWS_S3_BUCKET_IMAGES: ${AWS_S3_BUCKET_IMAGES:-gratitude-imagens-frontend}
      AWS_S3_BUCKET_APOSTILAS: ${AWS_S3_BUCKET_APOSTILAS:-gratitude-apostilas}
      JWT_SECRET: ${JWT_SECRET}
      JWT_VALIDITY: ${JWT_VALIDITY:-3600000}
      SPRING_RABBITMQ_HOST: ${SPRING_RABBITMQ_HOST:-rabbitmq}
      SPRING_RABBITMQ_PORT: ${SPRING_RABBITMQ_PORT:-5672}
      SPRING_RABBITMQ_USERNAME: ${SPRING_RABBITMQ_USERNAME:-capacita_rabbit}
      SPRING_RABBITMQ_PASSWORD: ${SPRING_RABBITMQ_PASSWORD:-CapacitaRabbit123}
      SPRING_RABBITMQ_LISTENER_SIMPLE_AUTO_STARTUP: ${RABBITMQ_ENABLE_LISTENERS:-true}
      # Email Configuration (Gmail SMTP)
      MAIL_HOST: ${MAIL_HOST:-smtp.gmail.com}
      MAIL_PORT: ${MAIL_PORT:-587}
      MAIL_USERNAME: ${MAIL_USERNAME:-}
      MAIL_PASSWORD: ${MAIL_PASSWORD:-}
       # Redis Cache
      CACHE_TYPE: redis
      REDIS_HOST: redis
      REDIS_PORT: 6379
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - rabbitmq
      - mailhog
      - redis
    restart: unless-stopped

volumes:
  rabbitmq_data:
  redis_data:
