version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - "5672:5672"      # AMQP port (protocolo)
      - "15672:15672"    # Management Console → http://localhost:15672 (guest/guest)
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - capacita-net
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      timeout: 10s
      retries: 10
      interval: 3s
    restart: unless-stopped

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    hostname: mailhog
    ports:
      - "1025:1025"   # SMTP (aplicação envia para cá)
      - "8025:8025"   # Web UI (ver emails)
    networks:
      - capacita-net
    restart: unless-stopped

  api:
    image: amazoncorretto:21
    container_name: api-spring
    command: sh -c "mkdir -p /usr/share/api && java -jar /usr/share/api/app.jar"
    volumes:
      - /usr/share/api:/usr/share/api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/${DATABASE_NAME:-capacita}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: ${DATABASE_USER:-capacita_app}
      SPRING_DATASOURCE_PASSWORD: ${DATABASE_PASSWORD:-"#Gfcapacita123"}
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${HIBERNATE_DDL_AUTO:-none}
      SPRING_JPA_SHOW_SQL: ${SHOW_SQL:-false}
      AWS_REGION: ${AWS_REGION:-us-east-1}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_S3_BUCKET_BRONZE: ${AWS_S3_BUCKET_BRONZE}
      AWS_S3_BUCKET_SILVER: ${AWS_S3_BUCKET_SILVER}
      AWS_S3_BUCKET_GOLD: ${AWS_S3_BUCKET_GOLD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_VALIDITY: ${JWT_VALIDITY:-3600000}
      SPRING_RABBITMQ_HOST: ${SPRING_RABBITMQ_HOST:-rabbitmq}
      SPRING_RABBITMQ_PORT: ${SPRING_RABBITMQ_PORT:-5672}
      SPRING_RABBITMQ_USERNAME: ${SPRING_RABBITMQ_USERNAME:-capacita_rabbit}
      SPRING_RABBITMQ_PASSWORD: ${SPRING_RABBITMQ_PASSWORD:-CapacitaRabbit123}
      SPRING_RABBITMQ_LISTENER_SIMPLE_AUTO_STARTUP: false
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - rabbitmq
    networks:
      - capacita-net
    restart: unless-stopped

networks:
  capacita-net:
    driver: bridge

volumes:
  rabbitmq-data:
  mysql-data:
