name: CI/CD para EC2 pública e privada

on:
  push:
    branches:
      - main # O branch que acionará o deploy

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do código
      - name: Checkout do Repositório
        uses: actions/checkout@v4

      # 2. Configuração do ambiente Java/Maven
      - name: BE - Configurar JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      # 3. (Opcional) Execução dos testes automatizados
      # - name: BE - Executar Testes automatizados
      #   run: mvn clean test

      # 4. Geração do .jar
      - name: BE - Gerar Artefato .JAR
        run: mvn clean package -DskipTests=true
        working-directory: ./

      # 5. Dando o mesmo nome sempre ao .jar
      - name: BE - Renomear JAR para app_loko.jar
        run: |
          set -e
          JAR_NAME=$(ls target/*.jar | head -n 1)
          mv "$JAR_NAME" target/app_loko.jar
          echo "Renomeado para: target/app_loko.jar"
        working-directory: ./

      # 6. Copiar JAR diretamente para o local de produção (/usr/share/api)
      - name: BE - Copiar JAR para /usr/share/api (rsync com sudo remoto)
        uses: easingthemes/ssh-deploy@main
        with:
          DROPLET_SSH_KEY: ${{ secrets.DROPLET_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: /usr/share/api/
          ARGS: "-rltgoDzvO --delete --rsync-path=\"sudo mkdir -p /usr/share/api && sudo rsync\""
          SOURCE: "./target/app_loko.jar"

      # 7. Reiniciar o serviço na Droplet
      - name: BE - Reiniciar serviço na Droplet
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            set -e
            echo "Reiniciando serviço 'api' na Droplet"
            sudo docker compose restart api || sudo docker-compose restart api
            echo "Serviço reiniciado em: ${{ secrets.REMOTE_HOST }}"
